services:
  - type: web
    name: ai-shniza
    build:
      pythonVersion: 3.11.8
      buildCommand: poetry install
    startCommand: poetry run python main.py
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11